/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nativeapi_anyMSG */

#ifndef _Included_com_nativeapi_anyMSG
#define _Included_com_nativeapi_anyMSG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nativeapi_anyMSG
 * Method:    login
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nativeapi_anyMSG_login
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
